#!/bin/sh
# use blkid instead of block, for block not detect ntfs partion

[ -z "$1" ] && {
	echo 'no device path'
	exit 1
}

enabled=1
[ "$2" == "0" ] && enabled=0
mount=0
[ "$2" == "2" ] && mount=1

set_fstab() {

	my_fstype=`blkid /dev/${device} | awk -F " TYPE=" '{print $2}'| awk -F "\"" '{print $2}'`
	
	[ -n "$my_fstype" ] && {
		logger -t Auto-Mount "New block.File system:${my_fstype}"
		if [ "$my_fstype" = 'swap' ]; then
			
			n=$(uci show fstab | grep "fstab.@swap" | grep -c "=swap")
			
			[ $n -gt 0 ] && {
				for i in $(seq 0 $n)
				do
					old_swap="$(uci get fstab.@swap[$i].device)"
					[ "$old_swap" = "/dev/$device" ] && {
						FLAG="SKIP"
						break
					}
				done
			}

			[ "$FLAG" != "SKIP" ] && {
				uci add fstab swap
				uci set fstab.@swap[$n]="swap"
				uci set fstab.@swap[$n].enabled='1'
				uci set fstab.@swap[$n].device="/dev/$device"
			}

		else

			case "$my_fstype" in
				hfs*)
					my_fstype="ufsd";;
				'ntfs')
					my_fstype="ufsd";;
				'exfat')
					my_fstype="ufsd";;
			esac

			options=""

			case "$my_fstype" in
				ext*)
					options="noatime";;
				btrfs)
					options="noatime";;
				ufsd)
					options="force,nls=utf8,uid=1023,gid=1023,umask=0007,noatime,user_xattr=1";;
				'vfat')
					options="utf8,uid=1023,gid=1023,dmask=0007,fmask=0007,shortname=mixed";;
                *)
                	enabled=0;;
			esac

			section=$(echo $get_uuid | sed 's/-//g')

			uci set fstab.${section}="mount"
			uci set fstab.${section}.enabled=$enabled
			uci set fstab.${section}.device="/dev/$device"
			uci set fstab.${section}.target="/mnt/${device}"
			uci set fstab.${section}.fstype="$my_fstype"
			[ -n "$options" ] && uci set fstab.${section}.options="$options"

			[ "$mount" == "1" -a "$enabled" == "1" ] && {
				[ -d "/mnt/${device}" ] || mkdir -p "/mnt/${device}"

				cmd="mount"
				[ -n "$my_fstype" ] && cmd="$cmd -t $my_fstype"
				[ -n "$options" ] && cmd="$cmd -o $options"
				cmd="$cmd /dev/$device /mnt/${device}"

				$cmd
			}
		fi
		return 0
	}
	return 1
}

blkdev=`dirname $1`
device=`basename $1`

if [ $device != "block" ]; then
	# Ignore nasroot(squashfs) and nasetc
	block info /dev/${device} | grep -q ' TYPE="squashfs"' && return 1
	block info /dev/${device} | grep -q ' LABEL="nasetc"' && return 1
	block info /dev/${device} | grep -q ' LABEL="rootfs_data"' && return 1
	get_uuid=`blkid /dev/${device} | awk -F " UUID=" '{print $2}'| awk -F "\"" '{print $2}'`
	[ -n "$get_uuid" ] && {
		logger -t Auto-Mount "Block /dev/${device} added."
		logger -t Auto-Mount "UUID=$get_uuid"
		/usr/sbin/blockdev --setra 16384 /dev/${device}
		have_uuid=$(uci show fstab | grep -c "$get_uuid")
		[ "$have_uuid" = "0" ] && {
			set_fstab || return 1
		}
		[ "$have_uuid" -gt "0" ] && {
			section=$(echo $get_uuid | sed 's/-//g')
			uci set fstab.${section}.target="/mnt/${device}"
		}
		return 0
	}
	return 1
fi
