#!/bin/sh
[ -f /etc/config/fstab ] || {
	echo "config 'global'" > /etc/config/fstab
	echo -e "\toption\tanon_swap\t'0'" >> /etc/config/fstab
	echo -e "\toption\tanon_mount\t'0'" >> /etc/config/fstab
	echo -e "\toption\tauto_swap\t'1'" >> /etc/config/fstab
	echo -e "\toption\tauto_mount\t'1'" >> /etc/config/fstab
	echo -e "\toption\tdelay_root\t'5'" >> /etc/config/fstab
	echo -e "\toption\tcheck_fs\t'0'" >> /etc/config/fstab
}

for DEVPATH in `blkid -o device`; do 
	enabled=0
	except=`basename $DEVPATH | grep -E "mmcblk|mtdblock"`
	[ -z "except" ] && enabled=1
	/sbin/add_fstab $DEVPATH "$enabled" >/dev/null
done

uci commit fstab >/dev/null

cp /etc/config/fstab /tmp/fstab
cat /tmp/fstab
rm -f /tmp/fstab