#!/bin/sh

[ -L /etc/config/netatalk ] || {
	[ -f /etc/config/netatalk ] && {
		cp -af /etc/config/netatalk /etc/config/afpd
		rm -f /etc/config/netatalk
	}
	ln -s afpd /etc/config/netatalk
}

[ -f /etc/init.d/netatalk ] && {
	/etc/init.d/netatalk disable
	rm -f /etc/init.d/netatalk
}

if [ "`uci get afpd.config.enabled`" == "1" ] ; then
	/etc/init.d/afpd enable
fi

uci -q batch <<-EOF >/dev/null
	delete ucitrack.afpd
	set ucitrack.afpd=afpd
	set ucitrack.afpd.init=afpd
	commit ucitrack
EOF

exit 0
