#!/bin/sh

/etc/init.d/vsftpd enabled && {
	/etc/init.d/vsftpd stop
	/etc/init.d/vsftpd disable
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.vsftpd
	set ucitrack.vsftpd=vsftpd
	set ucitrack.vsftpd.init=vsftpd
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
