#!/bin/sh

if [ "`uci get vsftpd.config.enabled`" == "1" ] ; then
	/etc/init.d/vsftpd enable
fi

uci -q batch <<-EOF >/dev/null
	delete ucitrack.vsftpd
	set ucitrack.vsftpd=vsftpd
	set ucitrack.vsftpd.init=vsftpd
	commit ucitrack
EOF

exit 0
