#!/bin/sh

[ -L /etc/config/samba ] || {
	[ -f /etc/config/samba ] && {
		cp -af /etc/config/samba /etc/config/samba4
		rm -f /etc/config/samba
	}
	ln -s samba4 /etc/config/samba
}

[ -f /etc/init.d/samba ] && {
	/etc/init.d/samba enabled && /etc/init.d/samba disable
}

exit 0