#!/bin/sh

SERVICES="samba minidlna transmission vsftpd forked-daapd netatalk"

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 SERVICENAME [enable|disable] "
  exit 1
fi

if echo "$SERVICES" | grep -q $1; then
	SERVICENAME=$1
	[ "$SERVICENAME" == "samba" ] && SERVICENAME="samba4"
	case "$2" in
		enable)
			/sbin/uci set $SERVICENAME.config.enabled=1
			/sbin/uci commit $SERVICENAME
			/etc/init.d/$SERVICENAME start
			/etc/init.d/$SERVICENAME enable
			exit 0
		;;

		disable)
			/sbin/uci set $SERVICENAME.config.enabled=0
			/sbin/uci commit $SERVICENAME
			/etc/init.d/$SERVICENAME stop
			/etc/init.d/$SERVICENAME disable
			exit 0
		;;

		*)
			echo "$2 command is not supported"
			exit 1
		;;
	esac
else
	echo "Service: $1 is not yet supported"
	exit 1
fi
