#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2012 OpenWrt.org

START=80
STOP=10

USE_PROCD=1

CONF_FILE='/etc/afp.conf'

config_instance()
{
    local hostname
    local path

    config_get hostname $1 hostname
    config_get path $1 path

    sed -i "/^path =/c\path = $path" $CONF_FILE
    sed -i "/^hostname =/c\hostname = $hostname" $CONF_FILE
}

start_service() {
	local enabled
	config_load afpd

	config_get_bool enabled config 'enabled' '0'

	[ "$enabled" -gt 0 ] || return 1

	config_foreach config_instance netatalk

	mkdir -p /var/netatalk/CNID/files

	procd_open_instance
	procd_set_param command /usr/sbin/afpd -d -F $CONF_FILE
	procd_set_param file $CONF_FILE
	procd_set_param respawn
	procd_close_instance

	procd_open_instance
	procd_set_param command /usr/sbin/cnid_metad -d
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	PROCD_RELOAD_DELAY=2000

	procd_add_reload_trigger "afpd"
}