#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
START=61

BIN=avahi-daemon
DEFAULT=/etc/default/$BIN
OPTIONS="--no-drop-root -D"
RUN_D=/var/run/$BIN

start() {
	[ -f $DEFAULT ] && . $DEFAULT
	mkdir -p $RUN_D
	$BIN $OPTIONS
}

stop() {
  $BIN -k
}

reload() {
  $BIN -r
}

