#!/bin/sh /etc/rc.common
# (C) 2013 openwrt.org
# 2019 jjm2473

START=40

fstab_add_mount() {
	local device
	local fstype
	local options
	local uuid
	local label
	local target
	local cmd

	config_get uuid "$1" 'uuid'
	if [ -z "$uuid" ] ; then
		config_get label "$1" 'label'
		if [ -z "$label" ] ; then
			config_get device "$1" 'device'
		else
			device=`blkid -o device -L $label`
		fi
	else
		device=`blkid -o device -U $uuid`
	fi

	[ -n "$device" ] && {
		config_get target "$1" 'target'

		[ -z "$target" ] && return 0

		config_get_bool enabled "$1" enabled 0

		if [ $enabled -gt 0 ] ; then
			# mount
			config_get fstype "$1" 'fstype'

			case "$fstype" in
				hfs*)
					fstype="ufsd";;
				'ntfs')
					fstype="ufsd";;
				'exfat')
					fstype="ufsd";;
			esac

			grep -q "^nodev\t$fstype\$" /proc/filesystems || [ -b "$device" ] || return 1

			# umount pre mountpoint
			grep -Fw "$device" /proc/mounts | awk -F " " '{print $2}' | xargs -rn1 umount

			[ "$?" == "0" ] && {
				[ -d "$target" ] || mkdir -p "$target"

				cmd="mount"
				[ -n "$fstype" ] && cmd="$cmd -t $fstype"
				config_get options "$1" 'options'
				[ -n "$options" ] && cmd="$cmd -o $options"
				cmd="$cmd $device $target"

				$cmd
			}
		else
			grep -q -Fw "$device $target" /proc/mounts && umount -r "$target"
		fi
	}
	
}

start() {
	config_load fstab
	config_foreach fstab_add_mount mount
}

reload() {
	start
}

stop() {
	sync
	find /mnt/ -maxdepth 1 -mindepth 1 -type d | xargs -rn1 umount -r
}
