#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
# 2019 copy from pandorabox

START=99
STOP=60

USE_PROCD=1

NFS_D=/var/lib/nfs
RECOVERY_D=$NFS_D/v4recovery
LOCK_D=/var/lib/nfs/sm
VAR_NFS=/var/lib/nfs

nfsd_wrap_cfg() {
	local cfg=$1
	config_get share_dir "$cfg" 'share_dir'
	config_get share_ip "$cfg" 'share_ip' '*'
	config_get share_options "$cfg" 'share_options' 'ro,insecure,sync'
	[ -z $share_dir ] && {
		echo "Config $cfg has no share_dir.ignore this."
		return
	}
	echo "${share_dir} ${share_ip}(${share_options})" >> /etc/exports
}

nfsd_cfg_gen() {
	echo > /etc/exports
	config_load 'nfsd'
	config_foreach nfsd_wrap_cfg 'nfsd_mount'
}

start_service() {
	nfsd_cfg_gen
	grep -q /proc/fs/nfsd /proc/mounts || \
		mount -t nfsd nfsd /proc/fs/nfsd
	mkdir -p $NFS_D
	mkdir -p $RECOVERY_D
	mkdir -p $LOCK_D
	touch $NFS_D/rmtab

	mkdir -p $VAR_NFS
	chown nfs:nfs $VAR_NFS

	sysctl -w fs.nfs.nlm_tcpport=32777 fs.nfs.nlm_udpport=32777 > /dev/null

	procd_open_instance
	procd_set_param command /usr/sbin/rpc.statd -p 32778 -o 32779 -F
	procd_close_instance

	/usr/sbin/exportfs -r
	/usr/sbin/rpc.nfsd --grace-time 10

	procd_open_instance
	procd_set_param command /usr/sbin/rpc.mountd -p 32780 -F
	procd_close_instance
}

stop_service() {
	rpc.nfsd 0 2> /dev/null
	/usr/sbin/exportfs -au
	grep -q /proc/fs/nfsd /proc/mounts && \
		umount /proc/fs/nfsd
}

reload_service() {
	nfsd_cfg_gen
	/usr/sbin/exportfs -r
}

service_triggers() {
	procd_add_reload_trigger "nfsd"
}