#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

STOP=90

restart() {
	:
}

stop() {
	sync
	find /mnt/ -maxdepth 1 -mindepth 1 -type d | xargs -n1 umount -r
	/bin/umount -a -d -r
}

shutdown() {
	stop
	/sbin/idle_sata
}
