#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2006 Carlos Sobrinho

START=09
STOP=97

USE_PROCD=1
PROG=/sbin/xubus
NAME=xubus

start_service()
{
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}

shutdown() {
	# close all open connections
	killall xubus
}
