#!/bin/sh

device=`basename $DEVPATH`
except=`echo $device | grep -E "mmcblk|mtdblock"`

if [ $device != "block" ] && [ -z $except ]; then

    case "$ACTION" in
		add)
			/sbin/add_fstab $DEVPATH "2" && {
				uci commit fstab
				sleep 1
				mountpoint=`sed -ne "s|^[^ ]*/$device ||; T; s/ .*//p" /proc/self/mounts`
				[ -n "$mountpoint" ] && chown nobody.media_rw $mountpoint && chmod 0775 $mountpoint
			}
			;;

		remove)
			umount /dev/${device}
			rmdir /mnt/${device}
			;;
    esac

fi
